[tool.poetry]
name = "pylinac"
version = "3.1.0"
description = "A toolkit for performing routine machine QA-related tasks in medical physics"
authors = ["James Kerns <jkerns100@gmail.com>"]
license = "MIT"
readme = "README.rst"
documentation = "https://pylinac.readthedocs.io/en/latest/"
repository = "https://github.com/jrkerns/pylinac"
keywords = ["medical", "physics", "image", "analysis"]
packages = [
    { include = "pylinac" }
]
include = ['pylinac/files/*.png']
classifiers=[
    "Intended Audience :: Developers",
    "Intended Audience :: Healthcare Industry",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
    "Topic :: Scientific/Engineering :: Image Recognition",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Software Development :: Libraries"
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
